.SUFFIXES: .o .f90

FC  =mpif90
#parallel-netcdf
#casper
NETCDF= /glade/u/apps/casper/24.12/spack/opt/spack/netcdf/4.9.2/oneapi/2024.2.1/hkzu
#derecho
#NETCDF= /glade/u/apps/derecho/24.12/spack/opt/spack/netcdf/4.9.2/oneapi/2024.2.1/uao5/
MPIPATH = /glade/u/apps/casper/24.12/spack/opt/spack/openmpi/5.0.6/oneapi/2024.2.1/ptm3
#/glade/u/apps/casper/24.12/spack/opt/spack/netcdf/4.9.2/openmpi/5.0.6/oneapi/2024.2.1/tlt6
NETCDF_LIB = ${NETCDF}/lib
NETCDF_INC = ${NETCDF}/include

LIBS=-L${NETCDF_LIB} -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm -L${MPIPATH}/lib -lmpi
INC =-I${NETCDF_INC} -I${MPIPATH}/include

#FCFLAGS=-O2 -ffree-line-length-none -w #-Wunused #-Wall 
#LDFLAGS=-O2
DEBUG = -g -traceback# -check all -fpe0 -O0
#DEBUG = -g -check all -traceback -O0
FCFLAGS= $(DEBUG) -O3  -extend-source #-Wunused #-Wall 
LDFLAGS= $(DEBUG) 

#OBJS= datetime_module.o megan_voc.o megan_nox.o megan_driver.o #bdsnp.o
OBJS= datetime_module.o megan_voc.o  megan_driver.o #bdsnp.o
EXE =../exe/megan_v3.3.exe

$(EXE): $(OBJS)
	$(FC) $(LDFLAGS) $(OBJS) $(LIBS) -o $(EXE)
%.o: %.f90
	$(FC) -c $(FCFLAGS) $(INC) $< -o $@
clean:
	rm -f *.o *.mod
